services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    env_file:
      - postgres.env
    deploy:
      resources:
        limits:
          memory: 250M

  nginx:
    image: nginx:latest
    configs:
      - source: vote.conf
        target: /etc/nginx/conf.d

  worker:
    build:
      context: https://github.com/UffizziCloud/example-voting-worker:main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build:
      context: https://github.com/UffizziCloud/example-voting-vote:main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result:main
      dockerfile: Dockerfile

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true

ingress:
  service: nginx
  port: 8080
