orbs:
  azure-acr: circleci/azure-acr@0.2.0
version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

workflows:
  build-deploy:
    jobs:
      - azure-acr/build-and-push-image:
          pre-steps:
            - run:
                command: export TAG=uffizzi_request_`echo $CIRCLE_PULL_REQUEST | grep '[^\/]*$' --only-matching`
          dockerfile: # defaults to `Dockerfile`
          path: # Defaults to working directory
          login-server-name: uffizziqa.azurecr.io # e.g. {yourregistryname}.azure.io
          registry-name: uffizziqa
          repo: example-worker
          tag: uffizzi_request_$TAG
          context:
            - test-acr-service-principal